# Numpy Foundations

## Leading Questions to be answered 
- The differences between a NumPy ndarray and nested lists in Python

- How to construct an ndarray

- NumPy's axis numbering system

- How to access and modify values in an ndarray

- Viewing vs Copying 

- NumPy operations - vectorization, broadcasting, and ufuncs


### NumPy Array

Let us first create a matrix and make a calculation with it using Python.

In [5]:
In [1]: matrix = [[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]]
In [2]: [[i + 1 for i in row] for row in matrix]

[[2, 3, 4], [5, 6, 7], [8, 9, 10]]

This way of coding is not very readable, and looping through each element will becomes very slow with larger arrays.

Using NumPy arrays instead of Python lists can help reduce runtime from a couple seconds to around a hundred times faster!

NumPy utilises code written in C or Fortran as they are compiled languages and run faster.

A NumPy array is an N-dimensional array for **homogenous data**.

Lets experiment with a 1D and 2D array

**NumPy labels their axis starting from zero, the x axis is "Axis 1" the y axis is "Axis 0"**

In [6]:
import numpy as np

In [7]:
array1 = np.array([10, 100, 1000.])
array2 = np.array([[1., 2., 3.],
                   [4., 5., 6.]])

*NumPy requires all the data to be of the same type, we can see this type with the* `dtype` *attribute*

In [8]:
array1.dtype

dtype('float64')

### Vectorization and Broadcasting

If you build the sum of a scalar(data type with a single element like a string, float, int, etc..) and a NumPy array, NumPy performs an element-wise operation, so you don't have to loop through elements yourself. This is refered to as ***vectorization***.

Vectorization allows you to write concise code.

For example:

In [ ]:
array2

In [9]:
array2 + 1

array([[2., 3., 4.],
       [5., 6., 7.]])

In [10]:
array2 * array2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

When dealing with two arrays with different shapes, if possible, NumPy extends the smaller array across the larger array. This is called ***Broadcasting***

In [11]:
array2 * array1

array([[  10.,  200., 3000.],
       [  40.,  500., 6000.]])

### Universal Functions

Universal Functions(***unfunc***) work on every element in a NumPy array.

Python does not allow you to use functions such as square root(sqrt) on a whole array but using unfun we can.

In [ ]:
array2

In [ ]:
math.sqrt(array2) # Python

In [ ]:
np.sqrt(array2) # Using unfunc

NumPy has some unfuncs that are avalible as array methods.

```axis = 0 ``` - refers to the rows
```axis = 1 ``` - refers to the columns
```axis ``` - sums up the whole array

In [ ]:
array2

In [22]:
array2.sum(axis=0) # Rows

array([5., 7., 9.])

In [21]:
array2.sum(axis=1) # Columns

array([ 6., 15.])

In [20]:
array2.sum() # Whole array

np.float64(21.0)

### Creating and Manipulating Arrays

In python to get a specific element in an array you do ```matrix[column][row]``` in NumPy it is in a single pair of brackets. ```numpy_array[row_selection, column_selection]```

In [ ]:
array1

In [23]:
array1[2]  # Returns a scalar

np.float64(1000.0)

In [ ]:
array2

In [24]:
array2[:, 1:]  # Returns a 2d array

array([[2., 3.],
       [5., 6.]])

In [25]:
array2[1, :2]  # Returns a 1d array

array([4., 5.])

```arange```: returns a squence of numbers starting from 0 to a specified number, in a NumPy array.

```reshaped```: Shapes your array how you specifiy.

```ones```: makes an array of 1s

```zeros```: makes an array of 0s

```eye```: makes an identity matrix

NumPy returns ***views*** when you slice them. Setting a value on a view will change the original array.

In [26]:
array2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
subset = array2[:, :2]
subset

In [ ]:
subset[0, 0] = 1000

In [ ]:
array2

To not change array2 you would need to do this

In [ ]:
subset = array2[:, :2].copy()

**Editing a view will edit the actual array, copying and then editing will not edit the actual array**

## Leading Questions answered 
- The differences between a NumPy ndarray and nested lists in Python
    - ndarray is faster, and more memmory-efficient.
    - nested lists are slower, and less optimized.
- How to construct an ndarray
    - Use np.array()
    - use other pre-defined arrays
- NumPy's axis numbering system
    - The x axis is 1 the y axis is 0
    - Starts with row 0 and column 0
- How to access and modify values in an ndarray
    - Use indexing
- Viewing vs Copying 
    - when editing a view you are editing the actual array
    - when editing a copy you are not editing the actual array
- NumPy operations - vectorization, broadcasting, and ufuncs
    - Vectorization applies operations to entire arrays.
    - Broadcasting alligns smaller arrays to larger array for operations
    - ```ufuncs``` perform element-wise functions